In [1]:
import timeit
import numpy as np

In [4]:
# Why use NumPy?
import time
import numpy as np

In [84]:
x = np.random.random(100000000)

float64


In [5]:
# Case 1
start = time.time()
sum(x) / len(x)
print(time.time() - start)

36.93174982070923


In [19]:
# Case 2
start = time.time()
np.mean(x)
print(time.time() - start)

0.17336535453796387


In [59]:
def np_array_characteristics(array):
    print(f'shape: {array.shape}\nsize: {array.size}\ndimensions (rank): {array.ndim}\ndtype: {array.dtype}')

# 1-D Array Characteristics

In [85]:
np_array_characteristics(x)

shape: (100000000,)
size: 100000000
dimensions (rank): 1
dtype: float64


In [86]:
a = np.array([1, 2, 3, 4, 6, 4])
np_array_characteristics(a)

shape: (6,)
size: 6
dimensions (rank): 1
dtype: int32


# 2-D Array Characteristics

In [61]:
y = np.array([["1","2","3","4","5","6"]])
print(y)
np_array_characteristics(y)

[['1' '2' '3' '4' '5' '6']]
shape: (1, 6)
size: 6
dimensions (rank): 2
dtype: <U1


# 3-D Array Characteristic

In [76]:
z = np.zeros((2, 3, 4))
print(z)
np_array_characteristics(z)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
shape: (2, 3, 4)
size: 24
dimensions (rank): 3
dtype: float64


# Mixed Array
Numpy array unlike python lists enforces a single data type in any array
* In case of ints and float the result is a float array **(upcasting)**
* In case of any string in the list mixed with number the result is a unicode array (array of strings)

In [73]:
mixed1 = np.array([1, 3, 4.3])
print(mixed1)
np_array_characteristics(mixed1)
#Numpy upcasted the array elments to float64 automatically

[1.  3.  4.3]
shape: (3,)
size: 3
dimensions (rank): 1
dtype: float64


In [75]:
mixed2 = np.array([1, "s"])
print(mixed2)
np_array_characteristics(mixed2)
#Numpy used unicode of 11 char for this array

['1' 's']
shape: (2,)
size: 2
dimensions (rank): 1
dtype: <U11


In [78]:
# Alternative way for the same result
# enforced = np.array([1, 3.4 ,2], dtype=np.int64)
enforced = np.array([1, 3.4 ,2]).astype(np.int64) #enforcing a specific datatype
print(enforced)
np_array_characteristics(enforced)

[1 3 2]
shape: (3,)
size: 3
dimensions (rank): 1
dtype: int64


# Saving & Loading Numpy Arrays

In [83]:
# We create a rank 1 ndarray
to_save = np.array([1, 2, 3, 4, 5])

# We save x into the current directory as 
np.save('my_array', to_save)

np_array_characteristics(to_save)

shape: (5,)
size: 5
dimensions (rank): 1
dtype: int32


In [82]:
# We load the saved array from our current directory into variable y
to_load = np.load('my_array.npy')
print(to_load)
np_array_characteristics(to_load)

[1 2 3 4 5]
shape: (5,)
size: 5
dimensions (rank): 1
dtype: int32
