In [2]:
import numpy as np

# Slicing rows and columns

In [3]:
X = np.arange(20).reshape(4, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [4]:
# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
print(X[1:4,2:5])
# We can select the same elements as above using method 2
print(X[1:,2:5])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [5]:
# We select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns
print(X[:3,2:5])

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [6]:
# We select all the elements in the 3rd row
print(X[2,:])

[10 11 12 13 14]


**Important Note:** selecting a column as a rank 1 array VS as a rank 2 array. 

In [7]:
# We select all the elements in the 3rd column
print(X[:,2])

# We select all the elements in the 3rd column but return a rank 2 ndarray
print(X[:,2:3])

[ 2  7 12 17]
[[ 2]
 [ 7]
 [12]
 [17]]


# Copying Arrays
Notice that previously slicing and assigning arrays to a variable is not copying the array.

The variable is just a view for the sliced part from the original array, meaning changing it would change the original array. (reference)

In [ ]:
# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)
print(X)

In [9]:
# create a copy of the slice using the np.copy() function
Z = np.copy(X[1:4,2:5])

#  create a copy of the slice using the copy as a method
W = X[1:4,2:5].copy()

# We change the last element in Z to 555
Z[2,2] = 555

# We change the last element in W to 444
W[2,2] = 444

# We print X
print()
print('X = \n', X)

# We print Z
print()
print('Z = \n', Z)

# We print W
print()
print('W = \n', W)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]

W = 
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 444]]


# More Than One Index to slice

In [10]:
X = np.arange(20).reshape(4, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [13]:
# We use the indices ndarray to select the 2nd and 4th row of X
Y = X[[1,3],:]

# We use the indices ndarray to select the 2nd and 4th column of X
Z = X[:, [1,3]]

print(Y, "\n")
print(Z)

[[ 5  6  7  8  9]
 [15 16 17 18 19]] 

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


# Slicing Diagonals

In [14]:
X = np.arange(25).reshape(5, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Notice that we used np.diag() previously to create a matrix with specified diagonal elements.

Now we use it to extract these values.

In [15]:
# We print the elements in the main diagonal of X
print('main', np.diag(X))

# We print the elements above the main diagonal of X
print('upper by 1', np.diag(X, k=1))

# We print the elements below the main diagonal of X
print('lower by 1', np.diag(X, k=-1))

main [ 0  6 12 18 24]
upper by 1 [ 1  7 13 19]
lower by 1 [ 5 11 17 23]


# Slicing Unique Elements

In [16]:
# Create 3 x 3 ndarray with repeated values
X = np.array([[1,2,3],[5,2,8],[1,2,3]])
print(X)

[[1 2 3]
 [5 2 8]
 [1 2 3]]


In [20]:
# We print the unique elements of X 
print('The unique elements in X are:',np.unique(X))

The unique elements in X are: [1 2 3 5 8]
