In [3]:
import numpy as np

# Generating General (Fixed) Matrices
* **zeros((shape)):** matrix of zeros with a specified shape.
* **ones((shape)) :** matrix of ones with a specified shape.
* **full((shape), number):** matrix of a specified number with a specificed shape.
* **eye(number):** generate an identity matrix, a _square_ matrix with number specifying the dimensions.
* **diag(\[list of number\]):** generate a square matrix with specified elements on the diagonal of the matrix.


In [2]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.full((3,4), 5) #full uses a constant to fill the array

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [6]:
np.eye(5) #create an identity matrix, taking an integer for the dimensions (square matrix)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
np.diag([1,2,3,4,5]) #create a square matrix with specified diagonal elements, taking a list of numbers.

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# Generate Range of numbers (1-D Arrays)

* **arange(start, stop, step):** a function works exactly like python range() function.
* **linspace(start, stop, n):** a function optimized to generate ranges with a floating points steps.

all generated numbers are "evenly spaced".

In [4]:
print(np.arange(10))
print(np.arange(4, 10))
print(np.arange(4, 10, 2))

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[4 6 8]


Unlike arange, linspace _requires_ a start, stop arguments.\
Also, the stop parameter is **inclusive** unlike arange method. To make this exclusive set the paramter **"endpoint" to False.**

linspace uses **"n"-number** of numbers instead of space argument in arange.
* If n is not specified the default is 50.

In [7]:
print( np.linspace(1, 10) ) # 50 number between 1 and 10
print( np.linspace(1, 10, 10) ) # 10 numbers between 1 and 10
print( np.linspace(0, 25, 10) ) # 10 numbers between 1 and 25

print( np.linspace(0, 25, 10, endpoint=False) ) # 10 numbers between 1 and 25 not including 25

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]
[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


Although linspace doesn't use steps, you could return the calculated step in the function by using **"retstep=True"**.

In [23]:
print( np.linspace(1, 10, 10, retstep=True) )

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)


# Using 1-D Arrays to create higher dimensions arrays (ReShape)
Main Rule: the new shape must be the same "size" as the old one.

In [15]:
print("1\n", np.reshape(np.arange(1,11), (2,5)) ) #function style

print("2\n", np.arange(1,11).reshape(2,5) ) #method style

print("3\n", np.arange(1, 13).reshape(2, 3, 2) ) #rank 3 array

1
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Generating Random Matrices
* **np.random.random((shape)):** generates random numbers between 0 up to 1 (exclusive)
* **np.random.randint(start, stop, (shape)):** generates random integers between start and stop (exclusive) to fill a specified shape

**Note:** if no shape is specified, the function will generate one number only.

In [19]:
print( np.random.random((3,3)) )
print( np.random.random() )

[[0.44128115 0.35695325 0.39877541]
 [0.93113697 0.46061855 0.51577007]
 [0.98059799 0.65836045 0.82624534]]
0.875035042294473


In [20]:
print( np.random.randint(1, 10, (3,3)) )

print( np.random.randint(1, 10) )

[[4 5 6]
 [1 1 9]
 [8 5 7]]
5


# Generating Statistical Matrices
* **np.random.normal(mu, std, (shape)):** normal distribution matrix

In [21]:
print( np.random.normal(0, 1, (3,3)))

[[-0.06790796  1.17822973 -2.33790485]
 [ 0.38127533  0.87225646 -0.47542695]
 [ 1.19533614  0.06508905  1.38844157]]
