In [2]:
import numpy as np

# 1-D Access & Modify

In [3]:
a = np.arange(1,10)

print(a)
print(f'a[0]: {a[0]}')
print(f'a[5]: {a[5]}')
print(f'a[-1]: {a[-1]}')

x = a[3]
print(x)
a[3] = 100
print(a)

[1 2 3 4 5 6 7 8 9]
a[0]: 1
a[5]: 6
a[-1]: 9
4
[  1   2   3 100   5   6   7   8   9]


# 2-D Access & Modify

In [4]:
b = np.arange(1,10).reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Working with specific elements 

In [5]:
print(f'b[0]: {b[0]} "complete row"')
print(f'b[2]: {b[2]} "complete row"')
print(f'b[-1]: {b[-1]} "complete row"')

print("\nBoth ways works the same for higher ranks:")
print(f'python like: b[-1][0]: {b[-1][0]}')
print(f'numpy like: b[-1, 0]: {b[-1, 0]}')

b[0]: [1 2 3] "complete row"
b[2]: [7 8 9] "complete row"
b[-1]: [7 8 9] "complete row"

Both ways works the same for higher ranks:
python like: b[-1][0]: 7
numpy like: b[-1, 0]: 7


Woking with rows and columns
* **For b[:][0]:** b[:] returns the whole matrix and [0] is just a regular index.
* **For b[:, 0]:** here you are selecting the whole rows **"b[:]"** then the first column **"b[:, 0]**. The result is the intersection between the matrix rows and the first column.

![Explaining](Images/L3-Matrix_Access.png)

In [6]:
print("Notic that when it cames to slicing the results is diffrent:")
print(f'python like: b[:][0]: {b[:][0]}')
print(f'numpy like: b[:, 1]: {b[:, 0]}')

Notic that when it cames to slicing the results is diffrent:
python like: b[:][0]: [1 2 3]
numpy like: b[:, 1]: [1 4 7]


In [7]:
b[:][0] = [3, 2, 1]
print(b)
b[0, :] = 100 # same as [100, 100, 100] (numpy broadcasting)
print("\n", b)

[[3 2 1]
 [4 5 6]
 [7 8 9]]

 [[100 100 100]
 [  4   5   6]
 [  7   8   9]]


# Delete Elements
* **np.delete(ndarray, [list of rows-cols- indices], axis):** delete rows or cols according to a list of indices.
* **Axis:** Axis along which we want to delete.\
If 1 then delete columns.\
If 0 then delete rows. **(default)**\
If None then **flatten the array** and then apply delete on it.

In [8]:
c = np.arange(1, 10).reshape((3,3))
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
c_deleted_rows = np.delete(c, [0], axis=0)
print(c_deleted_rows)

[[4 5 6]
 [7 8 9]]


In [10]:
c_deleted_cols = np.delete(c, [0, 1], axis=1)
print(c_deleted_cols)

[[3]
 [6]
 [9]]


In [11]:
c_deleted_items = np.delete(c, [0,2,3])
print(c.reshape(c.size)) #flatten the array
print(c_deleted_items) #Notice that the array is falttened and no longer be a matrix.

[1 2 3 4 5 6 7 8 9]
[2 5 6 7 8 9]


# Append Elements
* **np.delete(ndarray, [list of items with a correct shape], axis):** delete rows or cols according to a list of indices.

**Note:** Same as delete function, if no axis is specified the array will be flattened.

In [12]:
d = np.arange(1,10).reshape((3,3))
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
#append a row to this (3,3) matrix
np.append(d, [[1,2,3]], axis=0)

# notice that the shape of [ [1,2,3] ] is (1,3)
# which is the correct shape of a row for this matrix.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [14]:
#append a col to this (3,3) matrix
np.append(d, [[1], [2], [3]], axis=1)

# notice that the shape of [[1], [2], [3]] is (1,3)
# which is the correct shape of a row for this matrix.
# [[1],         [[1], [2], [3]]
#  [2],
#  [3]]

array([[1, 2, 3, 1],
       [4, 5, 6, 2],
       [7, 8, 9, 3]])

In [15]:
np.append(d, [1,2,3]) #flattend

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3])

# Insert Elements
* **np.insert(ndarray, index, [list of elements], axis):** specifiy an index to start inserting values after it.

In [16]:
e = np.arange(1, 10).reshape((3,3))
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
np.insert(e, 0, [1,2,3]) #for array e insert starting from index 0 the elements [1,2,3]

np.insert(e, [0], [1,2,3]) #for array e insert starting from index 0 the elements [1,2,3]

np.insert(e, 0, [10,11,12], axis=0) #for array e, insert the elements [10,11,12] at index 0 as a row (axis 0)

np.insert(e, [0], [10,11,12], axis=0) #for array e, insert the elements [10,11,12] at index 0 as a row (axis 0)

np.insert(e, [0], [[10,11,12]], axis=0)

np.insert(e, 0, [[10,11,12]], axis=0)

array([1, 2, 3, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.insert(e, [0,2], [10,11,12], axis=0) #for array e, insert the elements [10,11,12] at index 0 as a row (axis 0)

np.insert(e, [0,2], [[10,11,12]], axis=0)

array([[10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12],
       [ 7,  8,  9]])

In [30]:
np.insert(e, 0, [10,11,12], axis=1) #for array e, insert the elements [10,11,12] at index 0 as a col (axis 1)

array([[10,  1,  2,  3],
       [11,  4,  5,  6],
       [12,  7,  8,  9]])

In [37]:
np.insert(e, [0], [10,11,12], axis=1) #for array e, insert the elements [10,11,12] at index 0 as a col (axis 1)

array([[10, 11, 12,  1,  2,  3],
       [10, 11, 12,  4,  5,  6],
       [10, 11, 12,  7,  8,  9]])

In [41]:
np.insert(e, 0, [[10],[11],[12]], axis=1)

array([[10, 11, 12,  1,  2,  3],
       [10, 11, 12,  4,  5,  6],
       [10, 11, 12,  7,  8,  9]])

In [38]:
np.insert(e, [0], [[10],[11],[12]], axis=1) #for array e, insert the elements [10,11,12] at index 0 as a col (axis 1)

array([[10,  1,  2,  3],
       [11,  4,  5,  6],
       [12,  7,  8,  9]])

In [40]:
np.insert(e, [0,2], [[10],[11],[12]], axis=1) #for array e, insert the elements [10,11,12] at index 0 as a col (axis 1)

array([[10,  1,  2, 10,  3],
       [11,  4,  5, 11,  6],
       [12,  7,  8, 12,  9]])

In [42]:
np.insert(e, [0,2], [10,11,12], axis=1)

ValueError: shape mismatch: value array of shape (3,) could not be broadcast to indexing result of shape (2,3)

# Concatinating Arrays
* vstack(ndarray, ndarray): vertical stacking, stack matrices on top of each other. (top + bottom)
* hstack(ndarray, ndarray): horizontal stacking, stack marices side by side. (left + right)

**Note that the shapes of staking sides are important.**

In [56]:
w = np.array([1,2])               # shape(2,) ---> (1,2) broadcast
x = np.array([[3,4],[5,6]])       # shape(2,2)
error = np.array([1,2,3])         # shape(3,) ---> (1,3)

print(np.vstack((w,x))) #notic that the columns shape is what matters.

try:
    print(np.vstack((error,x))) # (1,"3") + (2,"2")
except Exception as e:
    print("shape error\n", e)

[[1 2]
 [3 4]
 [5 6]]
shape error
 all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2


In [61]:
y = np.array([[1],[2]])              #shape(2,1)
z = np.array([[3,4], [5,6]])         #shape(2,2)
error2 = np.array([1,2])             #shape(2,)  ---> shape(1,2) broadcast

print(np.hstack((y,z))) #notic that the rows shape is what matters.

try:
    print(np.hstack((error2,x))) # ("1",2) + ("2",2)
except Exception as e:
    print("shape error\n", e)

[[1 3 4]
 [2 5 6]]
shape error
 all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)
